version: 2
jobs:
  build:
    docker:
      - image: node:10
    working_directory: ~/ci
    steps:
      - checkout
      - run:
          name: Display node and npm informations
          command: npm version
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Install Puppeteer dependencies
          command: bash .circleci/setup_puppeteer.sh
      - run:
          name: Install tests apps dependencies
          command: npm ci --prefix=src/__tests__/__apps__/basic && npm ci --prefix=src/__tests__/__apps__/custom-error
      - run:
          name: 'Build'
          command: 'npm run build'
      - run:
          name: 'Tests'
          command: 'npm run test'
      - save_cache:
          paths:
            - ./node_modules
          key: npm-cache-{{ checksum "package-lock.json" }}
